"""Generate notices for the Python runtime embedded by ``omp-py``.

The python-build-standalone release describes CPython and each extension's
native link inputs in ``PYTHON.json``.  This generator follows that metadata,
reads the release's referenced license corpus, using one tracked, audited
upstream fallback for the release's missing Zstandard text, and then appends
license files from every frozen wheel. Any other missing referenced license is
a hard error. Dynamic host libraries are deliberately outside the
bundled-component corpus.

Usage: gen-py-notices.py VENDOR_DIR OUT
"""

from __future__ import annotations

import json
from pathlib import Path
import sys


AUDITED_LICENSE_FALLBACKS = {
    "licenses/LICENSE.zstd.txt": (
        "facebook/zstd v1.5.7 LICENSE",
        Path(__file__).resolve().parent.parent / "licenses" / "LICENSE.zstd.txt",
    ),
}

HEADER = """Third-party notices
===================

License information for CPython, native libraries statically linked from the
pinned python-build-standalone release, and pure-Python packages frozen into
omp-py binaries. Generated by omp-py's scripts/fetch-python.sh from the
fetched release metadata and license corpus — do not edit by hand.

Dynamic host libraries
----------------------
Libraries and frameworks that PYTHON.json marks as dynamic system dependencies
are supplied by the target operating system. They are not copied into the
python-build-standalone static library corpus and are intentionally excluded
from the bundled-component notices below.
"""


def fail(message: str) -> None:
    raise SystemExit(f"error: {message}")


def safe_release_path(vendor: Path, value: object, context: str) -> tuple[str, Path]:
    if not isinstance(value, str) or not value:
        fail(f"{context} has no license path")
    relative = Path(value)
    if relative.is_absolute() or ".." in relative.parts:
        fail(f"{context} has unsafe license path {value!r}")
    path = vendor.joinpath(relative)
    try:
        path.resolve().relative_to(vendor.resolve())
    except ValueError:
        fail(f"{context} license path escapes the release tree: {value!r}")
    return relative.as_posix(), path


def release_licenses(vendor: Path) -> tuple[str, dict[str, tuple[str, ...]], dict[str, Path]]:
    metadata_path = vendor / "PYTHON.json"
    try:
        metadata = json.loads(metadata_path.read_text(encoding="utf-8"))
    except (OSError, json.JSONDecodeError) as error:
        fail(f"cannot read {metadata_path}: {error}")

    version = metadata.get("python_version")
    if not isinstance(version, str) or not version:
        fail(f"{metadata_path} has no python_version")

    cpython_ref, cpython_path = safe_release_path(
        vendor, metadata.get("license_path"), "CPython"
    )
    references: dict[str, set[str]] = {"CPython": {cpython_ref}}
    corpus: dict[str, Path] = {cpython_ref: cpython_path}

    try:
        extensions = metadata["build_info"]["extensions"]
        variants = (
            variant
            for extension_variants in extensions.values()
            for variant in extension_variants
        )
    except (AttributeError, KeyError, TypeError) as error:
        fail(f"{metadata_path} has malformed build_info.extensions: {error}")

    for variant in variants:
        links = variant.get("links", ())
        static_names = []
        for link in links:
            if not isinstance(link, dict) or not isinstance(link.get("path_static"), str):
                continue
            name = link.get("name")
            if not isinstance(name, str) or not name:
                fail("static link entry has no component name")
            static_names.append(name)
        static_names = sorted(set(static_names))
        if not static_names:
            continue
        raw_paths = variant.get("license_paths")
        if not isinstance(raw_paths, list) or not raw_paths:
            fail(f"statically linked {', '.join(static_names)} has no license_paths")
        paths = [
            safe_release_path(vendor, value, f"native component {', '.join(static_names)}")
            for value in raw_paths
        ]
        for name in static_names:
            references.setdefault(name, set()).update(relative for relative, _ in paths)
        for relative, path in paths:
            corpus.setdefault(relative, path)

    return (
        version,
        {name: tuple(sorted(paths)) for name, paths in sorted(references.items())},
        dict(sorted(corpus.items())),
    )


def wheel_licenses(bundled: Path) -> list[tuple[str, str, list[Path]]]:
    if not bundled.is_dir():
        return []
    result = []
    for path in sorted(bundled.iterdir(), key=lambda item: item.name):
        if not path.name.endswith(".dist-info"):
            continue
        name, separator, version = path.name[: -len(".dist-info")].rpartition("-")
        if not separator:
            fail(f"cannot determine package name and version from {path.name}")
        license_dir = path / "licenses"
        if license_dir.is_dir():
            files = sorted(item for item in license_dir.rglob("*") if item.is_file())
        else:
            files = sorted(
                item
                for item in path.iterdir()
                if item.is_file()
                and item.name.upper().startswith(("LICENSE", "COPYING", "NOTICE"))
            )
        if not files:
            fail(f"{path.name} ships no license file")
        result.append((name, version, files))
    return result


def section(chunks: list[str], title: str, body: str) -> None:
    chunks.append(f"\n{title}\n{'-' * len(title)}\n{body.rstrip()}\n")


def generate(vendor: Path) -> tuple[str, int, int]:
    version, references, corpus = release_licenses(vendor)
    wheels = wheel_licenses(vendor / "bundled")
    chunks = [HEADER]

    lines = []
    for component, paths in references.items():
        label = f"CPython {version}" if component == "CPython" else component
        lines.append(label)
        lines.extend(f"  Authoritative release license reference: {path}" for path in paths)
    section(chunks, "Bundled CPython and static native components", "\n".join(lines))

    # A component may list several candidate license files and ship only the one
    # it was actually built against: the zlib extension names both
    # LICENSE.zlib-ng.txt and LICENSE.zlib.txt, and the release carries whichever
    # implementation it linked. A listed file the release omits is therefore not
    # automatically a gap in the notices — it is a gap only when nothing else
    # documents that component. Where a sibling does document it, the omitted
    # path is recorded below rather than substituted for, because inventing a
    # provenance line is worse than naming the absence.
    owners_of: dict[str, set[str]] = {}
    for component, component_paths in references.items():
        for candidate in component_paths:
            owners_of.setdefault(candidate, set()).add(component)
    documented = {
        component: any((vendor / candidate).is_file() for candidate in component_paths)
        for component, component_paths in references.items()
    }

    unshipped: list[tuple[str, tuple[str, ...]]] = []
    for relative, path in corpus.items():
        if path.is_file():
            title = f"python-build-standalone license corpus: {relative}"
            license_path = path
        else:
            owners = owners_of.get(relative, set())
            if owners and all(documented.get(owner) for owner in owners):
                unshipped.append((relative, tuple(sorted(owners))))
                continue
            fallback = AUDITED_LICENSE_FALLBACKS.get(relative)
            if fallback is None:
                fail(f"release metadata references absent license file {relative}")
            source, license_path = fallback
            if not license_path.is_file():
                fail(f"audited fallback for {relative} is absent: {license_path}")
            title = f"audited fallback for {relative} ({source})"
        section(chunks, title, license_path.read_text(encoding="utf-8"))

    if unshipped:
        lines = [
            "The release metadata lists these license files for components that are",
            "documented by another license file it does ship. They are named here so",
            "the omission is visible rather than silent.",
            "",
        ]
        lines.extend(
            f"  {relative} (listed for: {', '.join(owners)})" for relative, owners in unshipped
        )
        section(chunks, "Listed but not shipped by the release", "\n".join(lines))

    for name, package_version, files in wheels:
        for path in files:
            section(
                chunks,
                f"{name} {package_version} ({path.name})",
                path.read_text(encoding="utf-8"),
            )

    return "".join(chunks), len(references) - 1, len(wheels)


def main() -> None:
    if len(sys.argv) != 3:
        fail("usage: gen-py-notices.py VENDOR_DIR OUT")
    vendor = Path(sys.argv[1])
    out = Path(sys.argv[2])
    text, native_count, wheel_count = generate(vendor)
    try:
        stale = out.read_text(encoding="utf-8") != text
    except OSError:
        stale = True
    if stale:
        out.write_text(text, encoding="utf-8")
        print(
            f"{out.name}: updated ({native_count} static native components, "
            f"{wheel_count} frozen packages) — commit it",
            file=sys.stderr,
        )


if __name__ == "__main__":
    main()
